black:
  max:
  - 115
  - 135
  - 135
  min:
  - 0
  - 0
  - 0
blue:
  max:
  - 255
  - 255
  - 115
  min:
  - 0
  - 0
  - 0
green:
  max:
  - 200
  - 120
  - 150
  min:
  - 0
  - 0
  - 0
red:
  max:
  - 255
  - 255
  - 255
  min:
  - 0
  - 145
  - 130
white:
  max:
  - 255
  - 255
  - 255
  min:
  - 193
  - 0
  - 0
